# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f412d7b8f20d76bc69a036cd451f5a60ed39aef18779ec478b7dc5b23593873c7c6f9f4e5eb22366dc33ed96ace8e914db7253cb08b2fdcce7dfaa2ad667967

test:
  secret_key_base: 6d876ca42225c18a31e45e8fc5869a9824c42f702ee8bdc07d513ae50854031f71430a91d4eb77a8a6c66aaef2203dfdb88e46b49465b731fd41a2cab62f82c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
